# Generated by Django 2.0 on 2018-02-04 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0002_auto_20180204_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('p00', 'BlueJeans'), ('p01', 'Blusas'), ('p02', 'Chaquetas'), ('p03', 'Delantales'), ('p04', 'Guayaberas'), ('p05', 'Pantalonetas'), ('p06', 'Sudaderas')], max_length=3)),
                ('cantidad', models.PositiveIntegerField()),
                ('talla', models.PositiveIntegerField()),
                ('Colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Colegio')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='pedido',
            field=models.ManyToManyField(to='Facturación.Pedido'),
        ),
    ]
