# Generated by Django 2.0 on 2017-12-28 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueJeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrecioS', models.PositiveIntegerField()),
                ('PrecioM', models.PositiveIntegerField()),
                ('PrecioL', models.PositiveIntegerField()),
                ('Colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Colegio')),
            ],
        ),
        migrations.CreateModel(
            name='Blusas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrecioS', models.PositiveIntegerField()),
                ('PrecioM', models.PositiveIntegerField()),
                ('PrecioL', models.PositiveIntegerField()),
                ('Colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Colegio')),
            ],
        ),
        migrations.CreateModel(
            name='Chaquetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrecioS', models.PositiveIntegerField()),
                ('PrecioM', models.PositiveIntegerField()),
                ('PrecioL', models.PositiveIntegerField()),
                ('Colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Colegio')),
            ],
        ),
        migrations.CreateModel(
            name='Delantales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrecioS', models.PositiveIntegerField()),
                ('PrecioM', models.PositiveIntegerField()),
                ('PrecioL', models.PositiveIntegerField()),
                ('Colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Colegio')),
            ],
        ),
        migrations.CreateModel(
            name='Guayaberas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrecioS', models.PositiveIntegerField()),
                ('PrecioM', models.PositiveIntegerField()),
                ('PrecioL', models.PositiveIntegerField()),
                ('Colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Colegio')),
            ],
        ),
        migrations.CreateModel(
            name='Pantalonetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrecioS', models.PositiveIntegerField()),
                ('PrecioM', models.PositiveIntegerField()),
                ('PrecioL', models.PositiveIntegerField()),
                ('Colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Colegio')),
            ],
        ),
        migrations.CreateModel(
            name='Sudaderas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrecioS', models.PositiveIntegerField()),
                ('PrecioM', models.PositiveIntegerField()),
                ('PrecioL', models.PositiveIntegerField()),
                ('Colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Colegio')),
            ],
        ),
    ]
