# Generated by Django 2.0 on 2018-02-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_auto_20180204_1807'),
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guayaberas',
            new_name='BlueJean',
        ),
        migrations.RenameModel(
            old_name='Delantales',
            new_name='Blusa',
        ),
        migrations.RenameModel(
            old_name='Blusas',
            new_name='Chaqueta',
        ),
        migrations.RenameModel(
            old_name='Sudaderas',
            new_name='Delantale',
        ),
        migrations.RenameModel(
            old_name='Chaquetas',
            new_name='Guayabera',
        ),
        migrations.RenameModel(
            old_name='BlueJeans',
            new_name='Pantaloneta',
        ),
        migrations.RenameModel(
            old_name='Pantalonetas',
            new_name='Sudadera',
        ),
    ]
